name: MyEntities
version: 0.1
main: Benda95280\MyEntities\MyEntities
api: 3.0.0
author: Benda95280

permissions:
  MyEntities:
    description: Main permission
    default: op
    children:
      MyEntities.give:
        default: op
      MyEntities.spawn:
        default: op
      MyEntities.attack:
        default: op
