misc:
  #0 = No useless thing
  #1 = Just in console, when load
  #2 = Anything that can be useless !
  log-level: 0
message:
  message-head-added: '&a%s''s &aitem added in your inventory.'
skins:
  book_1:
    type: 'head'
    name: 'Nice Book'
    #RemoverTool can break it
    param:
      size: 'small'
      health: 1
      unbreakable: 1
  book_bible:
    type: 'head'
    name: 'Holy bible'
    param:
      size: 'normal'
      health: 10
      unbreakable: 0
  bowl_pasta:
    type: 'head'
    name: 'Pasta bowl'
    param:
      size: 'normal'
      health: 1
      unbreakable: 0
  calice:
    type: 'head'
    name: '&1Calice'
    param:
      size: 'block'
      health: 1
      unbreakable: 0
  crate_locked:
    type: 'head'
    name: 'Locked crate'
    param:
      size: 'block'
      health: 1
      unbreakable: 0