misc:
  #0 = No useless thing
  #1 = Just in console, when load
  #2 = Anything that can be useless !
  log-level: 0
message:
  message-head-added: '&a%s''s &aitem added in your inventory.'
skins:
  book_1:
    type: 'head'
    name: 'Nice Book'
    size: 0
  book_bible:
    type: 'head'
    name: 'Holy bible'
    size: 0
  bowl_pasta:
    type: 'head'
    name: 'Pasta bowl'
    size: 1
  calice:
    type: 'head'
    name: '&1Calice'
    size: 1
  crate_locked:
    type: 'head'
    name: 'Locked crate'
    size: 1